name: BuildAndPush

on:
  push:
    branches: [ main ]

jobs:
  build-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container & Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: polarizedions/buttbot/buttbot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
          dockerfile: ./ButtBot/Dockerfile
